version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm
    steps:
      - checkout
      - run: npm i
      - run: $(npm bin)/react-static build
      - run:
          command: $(npm bin)/serve dist -p 3939
          background: true
      - run: $(npm bin)/cypress run
