version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm
    steps:
      - checkout
      - run: npm ci
      - run: $(npm bin)/react-static build && $(npm bin)/serve dist -p 3939
      - run: $(npm bin)/cypress run
